#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -eu

# Type check, lint and test
npm run typecheck || exit 1
npm run lint || echo "No lint script or lint failed" && exit 1
npm test || exit 1

# Build package and docs
npm run build
npm run docs:build

# Verify artifacts
npm run verify:dist
npm run docs:build:check

# Verify version and tag
npm run verify:version
npm run verify:tag

# Dry run pack
npm pack --dry-run
